// @ts-check
/**
 * @description sidebars menu
 * @docs https://www.docusaurus.cn/docs/sidebar/items#sidebar-item-category
 */
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // 自动生成目录
    // tutorialSidebar: [{
    //     type: 'autogenerated', //类型
    //     dirName: 'dgiot' // 生成目录
    // }],
    // 手动定义目录
    docs: [{
            type: 'doc',
            id: 'news',
            label: '文档首页',
        },
        {
            type: 'category',
            label: 'classic_case',
            collapsible: true,
            collapsed: true,
            items: [{
                type: 'autogenerated',
                dirName: 'classic_case'
            }],
        },
        {
            type: 'category',
            label: 'user_manual',
            collapsible: true,
            collapsed: true,
            items: [{
                type: 'autogenerated',
                dirName: 'user_manual'
            }],
        },
        {
            type: 'category',
            label: 'product_doc',
            collapsible: true,
            collapsed: true,
            items: [{
                type: 'autogenerated',
                dirName: 'product_doc'
            }],
        },
        {
            type: 'category',
            label: 'practical_tutorial',
            collapsible: true,
            collapsed: true,
            items: [{
                type: 'autogenerated',
                dirName: 'practical_tutorial'
            }],
        },
        {
            type: 'category',
            label: 'developer_guid',
            collapsible: true,
            collapsed: true,
            items: [{
                type: 'autogenerated',
                dirName: 'developer_guid'
            }],
        }
    ],
};

module.exports = sidebars;